spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 199783118025-6uoibbd887iqchn2ts9bpsb0tbis8gbr.apps.googleusercontent.com
            client-secret: av9k5tyPVCaSb9rQ7Wgitd53

social:
  oauth2:
    client:
      registration:
        kakao:
          client-id: 230b5dd053d0ef1b234cb97fb27d0591
          client-secret: pgyUj8NHcKAaqJagAL8i46fIoqEbci2s